config/routes.rb
Rails.application.routes.draw do
  # resources :specialists
  # resources :messages
  resources :orders
  resources :themes
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post "messages" => "orders#message"
  post "specialists" => "persons#specialist"
  get 'specialists/accepted/:id', to: 'specialists#accepted', as: "accepted_specialist"
  get 'specialists/done/:id', to: 'specialists#done', as: "done_specialist"

  get 'home/index'
  get 'persons/profile', as: 'user_root'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/specialist.rb
class Specialist < ApplicationRecord
  belongs_to :order
  belongs_to :user
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_specialist, only: [:show, :edit, :update, :destroy]

  # GET /specialists
  # GET /specialists.json
  def index
    @specialists = Specialist.all
  end

  # GET /specialists/1
  # GET /specialists/1.json
  def show
  end

  # GET /specialists/new
  def new
    @specialist = Specialist.new
  end

  # GET /specialists/1/edit
  def edit
  end

  def accepted
    @specialist = Specialist.find(params[:id])
    @specialist.accepted = true

    respond_to do |format|
      if @specialist.update(specialist_params)
        format.html { redirect_to user_root_path }
      end
    end
  end

  def done
    @specialist = Specialist.find(params[:id])
    @specialist.done = true

    respond_to do |format|
      if @specialist.update(specialist_params)
        format.html { redirect_to user_root_path }
      end
    end
  end

  # POST /specialists
  # POST /specialists.json
  def create
    @specialist = Specialist.new(specialist_params)

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to @specialist, notice: 'Specialist was successfully created.' }
        format.json { render :show, status: :created, location: @specialist }
      else
        format.html { render :new }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialists/1
  # PATCH/PUT /specialists/1.json
  def update
    respond_to do |format|
      if @specialist.update(specialist_params)
        format.html { redirect_to @specialist, notice: 'Specialist was successfully updated.' }
        format.json { render :show, status: :ok, location: @specialist }
      else
        format.html { render :edit }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialists/1
  # DELETE /specialists/1.json
  def destroy
    @specialist.destroy
    respond_to do |format|
      format.html { redirect_to specialists_url, notice: 'Specialist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialist
      @specialist = Specialist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialist_params
      params.fetch(:specialist, {})
    end
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/specialists/_form.html.erb
<%= simple_form_for(@specialist) do |f| %>
  <div class="form-inputs">
    <%= f.input :order_id, :as => :hidden %>
    <%= f.input :user_id, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Подать заявку на участие в проекте' %>
  </div>
<% end %>

app/views/specialists/edit.html.erb
<h1>Editing Specialist</h1>

<%= render 'form', specialist: @specialist %>

<%= link_to 'Show', @specialist %> |
<%= link_to 'Back', specialists_path %>

app/views/specialists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Specialists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialists.each do |specialist| %>
      <tr>
        <td><%= link_to 'Show', specialist %></td>
        <td><%= link_to 'Edit', edit_specialist_path(specialist) %></td>
        <td><%= link_to 'Destroy', specialist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specialist', new_specialist_path %>

app/views/specialists/new.html.erb
<h1>New Specialist</h1>

<%= render 'form', specialist: @specialist %>

<%= link_to 'Back', specialists_path %>

app/views/specialists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_specialist_path(@specialist) %> |
<%= link_to 'Back', specialists_path %>