config/routes.rb
Rails.application.routes.draw do
  # resources :specialists
  # resources :messages
  resources :orders
  resources :themes
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post "messages" => "orders#message"
  post "specialists" => "persons#specialist"
  get 'specialists/accepted/:id', to: 'specialists#accepted', as: "accepted_specialist"
  get 'specialists/done/:id', to: 'specialists#done', as: "done_specialist"

  get 'home/index'
  get 'persons/profile', as: 'user_root'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  before_action :authenticate_user!

  def profile
    @search = Order.search(params[:q])

    @my_projects = Order.where(:user_id => current_user)
    @my_works = Specialist.where(:user_id => current_user, :done => 0)
    @specialists = Specialist.where(:order_id => @my_projects, :accepted => 0)
  end

  def specialist
    @specialist = Specialist.new(specialist_params)

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to user_root_path }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialist
      @specialist = Specialist.new(specialist_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialist_params
      params.require(:specialist).permit(:order_id, :user_id)
    end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/persons/profile.html.erb
<%= render file: 'template/header' %>
<a href="<%= new_order_path %>" class="button">Создать проект</a>
<ul class="tabs" data-tabs="data-tabs" id="example-tabs">
  <li class="tabs-title is-active">
    <a href="#panel1" aria-selected="true">Мои проекты</a>
  </li>
  <li class="tabs-title">
    <a data-tabs-target="panel2" href="#panel2">Участвую в проектах</a>
  </li>
  <li class="tabs-title">
    <a data-tabs-target="panel3" href="#panel3">Заявки на участие в моих проектах</a>
  </li>
</ul>
<div class="tabs-content" data-tabs-content="example-tabs">
  <div class="tabs-panel is-active" id="panel1">
      <% @my_projects.each do |order| %>
      <div class="grid-x grid-margin-x project">

        <div class="cell small-6 medium-2">
          <div class="project_image">
            <%= image_tag(order.picture_url) if order.picture? %>
          </div>
        </div>
        <div class="cell small-6 medium-2"><%= order.cost %>руб.<br><%= order.deadline %></div>
        <div class="cell small-12 medium-7"><%= order.description %></div>
        <div class="cell small-12 medium-1 edit-controls">
          <%= link_to order do %>
            <i class="fa fa-eye">&nbsp;</i>
          <% end %>
          <%= link_to edit_order_path(order) do %>
            <i class="fa fa-pencil">&nbsp;</i>
          <% end %>
          <%= link_to order, method: :delete, data: { confirm: 'Удалить проект?' } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </div>
        <div class="small-12">
          <hr>
        </div>
      </div>
<% end %>
</div>
<div class="tabs-panel" id="panel2">
  <div class="grid-x">
    <% @my_works.each do |w| %>
    <div class="cell small-12 medium-2">
      <%= w.created_at  %>
    </div>
    <div class="cell small-12 medium-9">
    <%= w.order.description %> <br>
    </div>
    <div class="cell small-12 medium-1">
      <%= link_to 'Завершить', done_specialist_path(w), :class => "button" %>
    </div>
    <% end %>
  </div>
</div>
<div class="tabs-panel" id="panel3">
  <div class="grid-x">
  <% @specialists.each do |s| %>
    <div class="cell small-12 medium-2">
      <%= s.created_at  %>
    </div>
    <div class="cell small-12 medium-3">
      <%= s.user.email %>
    </div>
    <div class="cell small-12 medium-6">
    <%= s.order.description %> <br>
    </div>
    <div class="cell small-12 medium-1">
      <%= link_to 'Принять', accepted_specialist_path(s), :class => "button" %>
    </div>
  <% end %>
</div>
</div>
</div>